<script setup lang="ts">
import { onMounted, ref } from "vue";
import { getApi, postApi } from "../utils/vue-api";
import { useAppStore } from "../stores/app";
import { RouterLink } from "vue-router";
const alerts = ref<any[]>([]); const loading = ref(true); const error = ref("");
const busyId = ref<number | null>(null);
const app = useAppStore();
onMounted(async () => { try { alerts.value = await getApi("/alerts"); } catch (e) { error.value = e instanceof Error ? e.message : "预警加载失败"; } finally { loading.value = false; } });
function dateLabel(value: string) { return value ? String(value).slice(0, 10) : "日期未知"; }
async function resolve(alert: any) { busyId.value = alert.id; error.value = ""; try { await postApi(`/alerts/${alert.id}/resolve`, {}); alert.status = "已处理"; app.setPendingAlertCount(alerts.value.filter((item) => item.status !== "已处理").length); } catch (e) { error.value = e instanceof Error ? e.message : "处理失败"; } finally { busyId.value = null; } }
</script>
<template><div class="view-head"><div><span class="kicker">需要人工核对</span><h2>经营预警中心</h2><p>先查看预警原因，完成现场处理后再标记“已处理”。</p></div></div><section class="panel"><div v-if="loading" class="empty">正在加载预警…</div><p v-if="error" class="empty error" role="alert">{{ error }}</p><div v-if="!loading && !error && !alerts.length" class="empty">当前没有经营预警。</div><div v-if="!loading && alerts.length" class="alert-list"><article v-for="alert in alerts" :key="alert.id" :class="{ resolved: alert.status === '已处理' }"><div class="level" :class="alert.risk_level === '高' ? 'high' : 'medium'">!</div><div class="content"><span>{{ alert.alert_type }} · {{ dateLabel(alert.business_date) }}</span><h3>{{ alert.dish_name }} · {{ alert.stall_name }}</h3><p>{{ alert.alert_message }}</p><RouterLink class="detail-link" :to="{ path: '/app/operations/feedback', query: { dishId: alert.dish_id } }">核对该菜经营记录 →</RouterLink></div><div class="actions"><b>{{ alert.risk_level }}风险</b><button v-if="alert.status !== '已处理'" class="btn" :disabled="busyId === alert.id" @click="resolve(alert)">{{ busyId === alert.id ? '处理中…' : '现场处理后标记' }}</button><small v-else>已处理</small></div></article></div></section></template>
<style scoped>.view-head{margin-bottom:22px}.kicker{font-size:10px;color:#3478c9;font-weight:700}.view-head h2{font-size:30px;margin:8px 0}.view-head p{color:#6f879f;font-size:13px}.panel{background:#fff;border:1px solid #dce8f2;border-radius:12px;padding:20px}.alert-list article{display:flex;align-items:center;gap:14px;border-top:1px solid #edf2f0;padding:16px 0}.level{width:36px;height:36px;border-radius:10px;display:grid;place-items:center;font-weight:800}.high{background:#fde9e7;color:#c75b52}.medium{background:#fff2dd;color:#c67a27}.content{flex:1}.content>span{font-size:10px;color:#82958e}.content h3{margin:6px 0;font-size:13px}.content p{margin:0;font-size:11px;color:#6f879f}.actions{text-align:right}.actions b{display:block;font-size:10px;color:#bd6d38}.actions small{font-size:10px;color:#3478c9}.btn{margin-top:8px;border:1px solid #d5e6f5;background:#fff;border-radius:6px;padding:7px 9px;font-size:10px;cursor:pointer}.resolved{opacity:.55}.empty{padding:45px;text-align:center;color:#8098ae}.error{color:#bd5c51}@media(max-width:650px){.alert-list article{align-items:flex-start}.actions{margin-left:auto}.content p{line-height:1.6}}
.detail-link{display:inline-block;margin-top:7px;font-size:12px;color:#286daf;font-weight:700}.btn{min-height:42px;font-size:12px}.content h3{font-size:15px}.content p{font-size:13px;line-height:1.6}@media(max-width:650px){.alert-list article{display:grid;grid-template-columns:36px minmax(0,1fr)}.actions{grid-column:2;text-align:left;margin-left:0}.actions b{display:inline-block;margin-right:10px}}
</style>
