<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useRoute } from "vue-router";
import { getApi } from "../utils/vue-api";
const route = useRoute(); const dashboard = ref<any>({}); const backtest = ref<any>({}); const loading = ref(true); const error = ref("");
const mode = computed(() => String(route.meta.insight || "realtime"));
const title = computed(() => mode.value === "demand" ? "需求预测分析" : mode.value === "waste" ? "减损场景分析" : "实时经营分析");
const description = computed(() => mode.value === "demand" ? "用历史趋势与模型结果辅助需求判断。" : mode.value === "waste" ? "量化剩余、优惠挽回和资源节约。" : "实时观察销量、剩余和经营健康度。");
onMounted(async () => { try { [dashboard.value, backtest.value] = await Promise.all([getApi("/operations/dashboard"), getApi("/analytics/backtest")]); } catch (e) { error.value = e instanceof Error ? e.message : "分析数据加载失败"; } finally { loading.value = false; } });
const summary = computed(() => dashboard.value.summary || {}); const rows = computed(() => dashboard.value.risks || []);
</script>
<template><div class="view-head"><div><span class="kicker">BUSINESS INSIGHT</span><h2>{{ title }}</h2><p>{{ description }}</p></div></div><div v-if="loading" class="state">正在加载分析数据…</div><div v-else-if="error" class="state error">{{ error }}</div><template v-else><div class="metric-grid"><article><span>当日备餐</span><strong>{{ summary.prepared ?? 0 }}</strong><small>份</small></article><article><span>当日售出</span><strong>{{ summary.sold ?? 0 }}</strong><small>份</small></article><article><span>闭餐剩余</span><strong>{{ summary.leftover ?? 0 }}</strong><small>份</small></article><article class="accent"><span>{{ mode === 'demand' ? '增强模型 MAPE' : mode === 'waste' ? '优惠挽回' : '售罄率' }}</span><strong>{{ mode === 'demand' ? (backtest.enhanced?.mape ?? '—') + '%' : mode === 'waste' ? (summary.rescued ?? 0) + '份' : (summary.prepared ? Math.round(summary.sold * 100 / summary.prepared) : 0) + '%' }}</strong><small>经营台账计算</small></article></div><div class="insight-grid"><section class="panel"><div class="panel-head"><span class="kicker">{{ mode === 'demand' ? 'MODEL BACKTEST' : mode === 'waste' ? 'WASTE CONTROL' : 'LIVE SNAPSHOT' }}</span><h3>{{ mode === 'demand' ? '预测模型效果' : mode === 'waste' ? '餐品流向概览' : '经营健康度' }}</h3></div><div class="bars"><div v-for="(point, index) in (dashboard.trend || []).slice(-7)" :key="index"><span>{{ String(point.businessDay ?? point.business_day).slice(5, 10) }}</span><i :style="{ height: `${Math.min(100, Number(point.sold || 0) / Math.max(1, Number(point.prepared || 1)) * 100)}%` }"></i><b>{{ point.sold }}</b></div></div></section><section class="panel"><div class="panel-head"><span class="kicker">RISK SNAPSHOT</span><h3>需要关注的菜品</h3></div><div class="risk-list"><div v-for="risk in rows" :key="risk.name"><span>{{ risk.name }}</span><b>{{ risk.risk_level }}风险</b><small>剩余 {{ risk.leftover_qty }} 份</small></div></div></section></div></template></template>
<style scoped>.view-head{margin-bottom:22px}.kicker{font-size:10px;color:#3478c9;font-weight:700}.view-head h2{font-size:30px;margin:8px 0}.view-head p{color:#6f879f;font-size:13px}.metric-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:16px}.metric-grid article,.panel{background:#fff;border:1px solid #dce8f2;border-radius:12px}.metric-grid article{padding:18px}.metric-grid span,.metric-grid small{display:block;color:#8098ae;font-size:10px}.metric-grid strong{display:block;margin:11px 0 6px;font:700 28px Manrope}.accent{background:#3478c9!important;color:#fff}.accent span,.accent strong,.accent small{color:#fff}.insight-grid{display:grid;grid-template-columns:1.25fr .75fr;gap:16px}.panel{padding:20px}.panel h3{margin:6px 0 20px}.bars{height:230px;display:flex;align-items:end;gap:12px;border-bottom:1px solid #dfeae5;padding:0 8px}.bars>div{height:100%;flex:1;display:flex;flex-direction:column;align-items:center;justify-content:end;gap:6px}.bars span,.bars b{font-size:9px;color:#82958e}.bars i{display:block;width:70%;max-width:34px;border-radius:6px 6px 0 0;background:linear-gradient(#51b993,#3478c9);min-height:4px}.bars b{color:#356456}.risk-list div{display:grid;grid-template-columns:1fr auto;gap:7px;padding:13px 0;border-top:1px solid #edf2f0}.risk-list span{font-size:12px}.risk-list b{font-size:10px;color:#bd7138}.risk-list small{grid-column:1/-1;color:#82958e;font-size:10px}.state,.error{padding:40px;background:#fff;border-radius:12px;color:#8098ae}.error{color:#bd5c51}@media(max-width:700px){.metric-grid{grid-template-columns:1fr 1fr}.insight-grid{grid-template-columns:1fr}}
</style>
