<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { getApi, postApi } from "../utils/vue-api";
import { dishPhoto } from "../utils/dish-photo";
const offers = ref<any[]>([]); const dishes = ref<any[]>([]); const selectedDish = ref<number | null>(null); const recommendation = ref<any>(null); const loading = ref(true); const busy = ref(false); const publishing = ref(false); const message = ref(""); const error = ref(""); const loadError = ref(""); const safetyConfirmed = ref(false);
const selectedName = computed(() => dishes.value.find((dish) => dish.id === selectedDish.value)?.name);
onMounted(async () => { try { [offers.value, dishes.value] = await Promise.all([getApi("/offers"), getApi("/dishes")]); selectedDish.value = dishes.value[0]?.id ?? null; } catch (e) { loadError.value = e instanceof Error ? e.message : "优惠数据加载失败"; } finally { loading.value = false; } });
async function recommend() { if (!selectedDish.value) return; busy.value = true; error.value = ""; safetyConfirmed.value = false; try { recommendation.value = await postApi("/intelligence/offers/recommend", { dishId: selectedDish.value }); } catch (e) { error.value = e instanceof Error ? e.message : "推荐失败"; } finally { busy.value = false; } }
async function publish() { if (!recommendation.value || !safetyConfirmed.value) return; publishing.value = true; error.value = ""; message.value = ""; try { await postApi("/offers", { dishId: recommendation.value.dishId, quantity: recommendation.value.recommendedQty, offerPrice: recommendation.value.recommendedPrice, startTime: recommendation.value.startTime, endTime: recommendation.value.endTime, safetyConfirmed: safetyConfirmed.value }); offers.value = await getApi("/offers"); message.value = "优惠活动已发布；只有已有订单才能在订单页核销。"; recommendation.value = null; safetyConfirmed.value = false; } catch (e) { error.value = e instanceof Error ? e.message : "发布失败"; } finally { publishing.value = false; } }
</script>
<template>
  <div class="view-head"><div><span class="kicker">营业中 · 第二步</span><h2>把剩余风险转化为动作</h2><p>先录入今天的经营记录，再确认实物剩余与安全售卖时间。优惠建议不会自动代替现场判断。</p></div></div>
  <div v-if="loading" class="state">正在加载优惠数据…</div>
  <div v-else-if="loadError" class="state error">{{ loadError }}</div>
  <template v-else>
    <section class="panel recommend">
      <div><span class="kicker">先生成，再核对</span><h3>选择菜品生成优惠方案</h3></div>
      <div class="recommend-form"><select v-model="selectedDish" aria-label="选择菜品"><option v-for="dish in dishes" :key="dish.id" :value="dish.id">{{ dish.name }}</option></select><button class="btn primary" :disabled="busy" @click="recommend">{{ busy ? "计算中…" : "生成建议" }}</button></div>
      <div v-if="dishPhoto(selectedName)" class="selected-photo"><img :src="dishPhoto(selectedName)!" :alt="`${selectedName}同类菜品实拍示意`" width="112" height="80"><span>同类菜品实拍示意<br>发布前请以现场实物为准</span></div>
      <div v-if="recommendation" class="recommend-result"><strong>{{ recommendation.dishName }}</strong><span>建议 {{ recommendation.recommendedQty }} 份 · ¥{{ recommendation.recommendedPrice }} · {{ recommendation.discountRate }}% 折扣 · {{ recommendation.startTime }}–{{ recommendation.endTime }}</span><p>{{ recommendation.advice?.summary || "建议在当餐安全售卖时段内执行。" }}</p><label class="safety-check"><input v-model="safetyConfirmed" type="checkbox"> 我已核对实物状态、库存及食品安全售卖时间</label><button class="btn primary" :disabled="publishing || !safetyConfirmed" @click="publish">{{ publishing ? "发布中…" : "确认发布优惠" }}</button></div>
      <p v-if="message" class="success">{{ message }}</p><p v-if="error" class="error" role="alert">{{ error }}</p>
    </section>
    <section class="panel"><div class="panel-head"><span class="kicker">活动清单</span><h3>已发布的限时优惠</h3></div><div v-if="!offers.length" class="empty">当前暂无优惠活动。</div><div v-else class="offer-list"><article v-for="offer in offers" :key="offer.id"><img v-if="dishPhoto(offer.dish_name ?? offer.dishName)" :src="dishPhoto(offer.dish_name ?? offer.dishName)!" :alt="`${offer.dish_name ?? offer.dishName}同类菜品实拍示意`" width="64" height="64" loading="lazy"><b>{{ offer.discount_rate ?? offer.discountRate }}%</b><div><strong>{{ offer.dish_name ?? offer.dishName }}</strong><span>{{ offer.remaining_qty ?? offer.remainingQty }} 份待领取 · ¥{{ offer.offer_price ?? offer.offerPrice }}</span></div><small>{{ offer.status || "进行中" }}</small></article></div></section>
  </template>
</template>
<style scoped>.view-head{margin-bottom:22px}.kicker{font-size:10px;color:#3478c9;font-weight:700}.view-head h2{font-size:30px;margin:8px 0}.view-head p{color:#6f879f;font-size:13px}.panel{background:#fff;border:1px solid #dce8f2;border-radius:12px;padding:20px;margin-bottom:16px}.panel h3{margin:6px 0 18px}.recommend-form{display:flex;gap:10px}.recommend-form select{flex:1;padding:11px;border:1px solid #d5e6f5;border-radius:7px}.btn{border:0;border-radius:8px;padding:11px 16px;font-weight:700;cursor:pointer}.primary{background:#3478c9;color:#fff}.recommend-result{margin-top:16px;padding:15px;background:#eaf3ff;border-radius:8px}.recommend-result strong,.recommend-result span{display:block}.recommend-result span{font-size:12px;color:#4b91d2;margin-top:7px}.recommend-result p{font-size:11px;color:#69857a}.offer-list article{display:flex;align-items:center;gap:14px;border-top:1px solid #edf2f0;padding:14px 0}.offer-list article>b{display:grid;place-items:center;width:42px;height:42px;border-radius:50%;background:#fff0df;color:#d47427;font:700 13px Manrope}.offer-list article strong,.offer-list article span{display:block}.offer-list article span{font-size:10px;color:#82958e;margin-top:5px}.offer-list small{margin-left:auto;color:#3478c9;font-size:10px}.state,.empty{padding:40px;text-align:center;color:#8098ae}.error{color:#bd5c51}@media(max-width:600px){.recommend-form{display:block}.recommend-form button{margin-top:10px;width:100%}}
.safety-check{display:flex;align-items:center;gap:8px;margin:12px 0;font-size:13px;line-height:1.5;color:#426680}.safety-check input{width:16px;height:16px}.btn:disabled{opacity:.5;cursor:not-allowed}.success{color:#16734d;font-size:13px}
</style>
<style scoped>
.selected-photo{display:flex;align-items:center;gap:12px;margin-top:14px;color:#5b7388;font-size:12px;line-height:1.6}.selected-photo img,.offer-list img{flex:none;object-fit:cover;border-radius:5px;background:#eef3f6}.selected-photo img{width:112px;height:80px}.offer-list img{width:64px;height:64px}@media(max-width:600px){.offer-list article{gap:8px}.offer-list img{width:52px;height:52px}.offer-list small{white-space:nowrap}}
</style>
