<script setup lang="ts">
import { onMounted, ref } from "vue";
import { getApi } from "../utils/vue-api";
const report = ref<any>({}); const backtest = ref<any>({}); const loading = ref(true); const error = ref("");
onMounted(async () => { try { [report.value, backtest.value] = await Promise.all([getApi("/reports"), getApi("/analytics/backtest")]); } catch (e) { error.value = e instanceof Error ? e.message : "报告加载失败"; } finally { loading.value = false; } });
const pick = (key: string, fallback = 0) => Number(backtest.value?.[key] ?? report.value?.summary?.[key] ?? fallback);
</script>
<template><div class="view-head"><div><span class="kicker">经营数据总览</span><h2>把经营变化算清楚</h2><p>依据统一经营台账，比较基线期与策略期的经营结果。</p></div></div><div v-if="loading" class="state">正在生成复盘报告…</div><div v-else-if="error" class="state error">{{ error }}</div><template v-else><div class="metric-grid"><article><span>预测样本</span><strong>{{ backtest.samples ?? "—" }}</strong><small>条回测记录</small></article><article><span>增强模型 MAPE</span><strong>{{ backtest.enhanced?.mape ?? "—" }}%</strong><small>滚动回测误差</small></article><article><span>基线模型 MAPE</span><strong>{{ backtest.baseline?.mape ?? "—" }}%</strong><small>对照模型</small></article><article class="accent"><span>结论口径</span><strong>可追溯</strong><small>数据来自授权台账</small></article></div><section class="panel"><div class="panel-head"><span class="kicker">复盘摘要</span><h3>指标变化</h3></div><div class="report-grid"><div><span>策略期剩余率</span><strong>{{ pick("intervention_leftover_rate") }}%</strong></div><div><span>基线期剩余率</span><strong>{{ pick("baseline_leftover_rate") }}%</strong></div><div><span>建议执行率</span><strong>{{ pick("adoption_rate") }}%</strong></div><div><span>剩余成本改善</span><strong>¥{{ report.summary?.avoided_loss ?? 0 }}</strong></div></div></section><section class="panel"><div class="panel-head"><span class="kicker">数据治理</span><h3>经营复盘闭环</h3></div><div class="steps"><div><b>01</b><span>统一导入经营资料</span></div><div><b>02</b><span>校验备餐、售出与剩余</span></div><div><b>03</b><span>更新需求基线与模型</span></div><div><b>04</b><span>沉淀下一周期动作</span></div></div></section></template></template>
<style scoped>.view-head{margin-bottom:22px}.kicker{font-size:10px;color:#3478c9;font-weight:700}.view-head h2{font-size:30px;margin:8px 0}.view-head p{color:#6f879f;font-size:13px}.metric-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:16px}.metric-grid article,.panel{background:#fff;border:1px solid #dce8f2;border-radius:12px}.metric-grid article{padding:18px}.metric-grid span,.metric-grid small{display:block;color:#8098ae;font-size:10px}.metric-grid strong{display:block;margin:11px 0 6px;font:700 28px Manrope}.accent{background:#3478c9!important;color:#fff}.accent span,.accent strong,.accent small{color:#fff}.panel{padding:20px;margin-bottom:16px}.panel h3{margin:6px 0 20px}.report-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.report-grid div{padding:15px;background:#f5f9fd;border-radius:8px}.report-grid span,.report-grid strong{display:block}.report-grid span{font-size:10px;color:#8098ae}.report-grid strong{font:600 18px Manrope;margin-top:9px}.steps{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.steps div{padding:18px;background:#eaf3ff;border-radius:8px}.steps b,.steps span{display:block}.steps b{font:700 18px Manrope;color:#3478c9}.steps span{font-size:11px;margin-top:8px}.state,.error{padding:40px;background:#fff;border-radius:12px;color:#8098ae}.error{color:#bd5c51}@media(max-width:700px){.metric-grid,.report-grid,.steps{grid-template-columns:1fr 1fr}}
</style>
